//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZERO.Material.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Apply_Info
    {
        public int Id { get; set; }
        public int Apply_Id { get; set; }
        public string ApplyType_Id { get; set; }
        public int Apply_Count { get; set; }
        public int Apply_Status { get; set; }
        public string Apply_Advice { get; set; }
    
        public virtual Apply_Type Apply_Type { get; set; }
    }
}
