//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZERO.Material.Model
{
    using System;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    
    public partial class Buy_Apply
    {
        public string Material_Id { get; set; }
        public string Material_Name { get; set; }
        public string Company_Name { get; set; }
        public double Material_Price { get; set; }
        public double Material_Count { get; set; }
        public string Material_Size { get; set; }
        public double Material_RemainCont { get; set; }
        public string Material_CountUnit { get; set; }
        public string ApplyType_Id { get; set; }
        public int Apply_Count { get; set; }
        public int Apply_Status { get; set; }
        public string Apply_Advice { get; set; }
        public System.DateTime Last_Time { get; set; }
        public int Apply_Id { get; set; }
        public bool Is_Bought { get; set; }
        public bool Is_InComed { get; set; }
        public string Material_Type_Name { get; set; }
    }
}
