//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZERO.Material.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material_Product
    {
        public Material_Product()
        {
            this.Material_Base_Product = new HashSet<Material_Base_Product>();
            this.Material_Product_Company = new HashSet<Material_Product_Company>();
        }
    
        public int Id { get; set; }
        public Nullable<System.DateTime> Update_Time { get; set; }
        public string Product_Id { get; set; }
        public string Product_Company_Id { get; set; }
        public string Product_Format { get; set; }
        public Nullable<double> Product_Price { get; set; }
        public string Product_Remark { get; set; }
    
        public virtual ICollection<Material_Base_Product> Material_Base_Product { get; set; }
        public virtual ICollection<Material_Product_Company> Material_Product_Company { get; set; }
    }
}
