//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZERO.Material.Model
{
    using System;using Newtonsoft.Json;
    using System.Collections.Generic;
    
    public partial class Material_Role
    {
        public int Id { get; set; }
        public string Role_Name { get; set; }
        public string Role_Remark { get; set; }
        public bool Del_Flag { get; set; }
    }
}
