//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZERO.Material.Model
{
    using System;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    
    public partial class Material_Teacher
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Material_Teacher()
        {
            this.Material_Apply = new HashSet<Material_Apply>();
            this.Material_Role_Teacher = new HashSet<Material_Role_Teacher>();
            this.Material_Teacher_Action = new HashSet<Material_Teacher_Action>();
        }
    
        public int Id { get; set; }
        public string Teacher_Id { get; set; }
        public string Teacher_Name { get; set; }
        public string Teacher_Depart { get; set; }
        public string Teacher_Password { get; set; }
        public Nullable<bool> Del_Flag { get; set; }
    
        [JsonIgnore]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Material_Apply> Material_Apply { get; set; }
        [JsonIgnore]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Material_Role_Teacher> Material_Role_Teacher { get; set; }
        [JsonIgnore]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Material_Teacher_Action> Material_Teacher_Action { get; set; }
    }
}
