//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZERO.Material.Model
{
    using System;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    
    public partial class Material_Role_Teacher
    {
        public int id { get; set; }
        public string Teacher_Id { get; set; }
        public int Role_Id { get; set; }
    
        public virtual Material_Role Material_Role { get; set; }
        public virtual Material_Teacher Material_Teacher { get; set; }
    }
}
