//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZERO.Material.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Material_Base_Type
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> Update_Time { get; set; }
        public string Material_Id { get; set; }
        public string Type_Id { get; set; }
    
        public virtual Material_Base Material_Base { get; set; }
        public virtual Material_Type Material_Type { get; set; }
    }
}
