//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZERO.Material.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material_Company
    {
        public Material_Company()
        {
            this.Material_Product_Company = new HashSet<Material_Product_Company>();
        }
    
        public int Id { get; set; }
        public Nullable<System.DateTime> Update_Time { get; set; }
        public string Company_Id { get; set; }
        public string Company_Name { get; set; }
        public string Company_Person { get; set; }
        public string Company_Person_Phone { get; set; }
        public string Company_Remark { get; set; }
    
        public virtual ICollection<Material_Product_Company> Material_Product_Company { get; set; }
    }
}
