//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZERO.Material.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ZERO_MaterialEntities : DbContext
    {
        public ZERO_MaterialEntities()
            : base("name=ZERO_MaterialEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Apply_Info> Apply_Info { get; set; }
        public virtual DbSet<Apply_Type> Apply_Type { get; set; }
        public virtual DbSet<BuyInComing_Apply> BuyInComing_Apply { get; set; }
        public virtual DbSet<Material_Action> Material_Action { get; set; }
        public virtual DbSet<Material_Apply> Material_Apply { get; set; }
        public virtual DbSet<Material_Base> Material_Base { get; set; }
        public virtual DbSet<Material_Base_Company> Material_Base_Company { get; set; }
        public virtual DbSet<Material_Base_Type> Material_Base_Type { get; set; }
        public virtual DbSet<Material_Company> Material_Company { get; set; }
        public virtual DbSet<Material_Role> Material_Role { get; set; }
        public virtual DbSet<Material_Role_Action> Material_Role_Action { get; set; }
        public virtual DbSet<Material_Role_Teacher> Material_Role_Teacher { get; set; }
        public virtual DbSet<Material_Teacher> Material_Teacher { get; set; }
        public virtual DbSet<Material_Teacher_Action> Material_Teacher_Action { get; set; }
        public virtual DbSet<Material_Type> Material_Type { get; set; }
        public virtual DbSet<Buy_Apply> Buy_Apply { get; set; }
        public virtual DbSet<Material_Info> Material_Info { get; set; }
        public virtual DbSet<Use_Apply> Use_Apply { get; set; }
    }
}
