//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZERO.Material.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material_Base
    {
        public Material_Base()
        {
            this.Material_Base_Product = new HashSet<Material_Base_Product>();
            this.Material_Base_Type = new HashSet<Material_Base_Type>();
        }
    
        public int Id { get; set; }
        public Nullable<System.DateTime> Update_Time { get; set; }
        public string Material_Id { get; set; }
        public string Material_Name { get; set; }
        public double Material_Count { get; set; }
        public double Material_Remain_Count { get; set; }
        public string Material_Count_Unit { get; set; }
        public string Material_Remark { get; set; }
    
        public virtual ICollection<Material_Base_Product> Material_Base_Product { get; set; }
        public virtual ICollection<Material_Base_Type> Material_Base_Type { get; set; }
    }
}
