//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZERO.Material.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ZERO_MaterialEntities : DbContext
    {
        public ZERO_MaterialEntities()
            : base("name=ZERO_MaterialEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Material_Base> Material_Base { get; set; }
        public DbSet<Material_Base_Product> Material_Base_Product { get; set; }
        public DbSet<Material_Base_Type> Material_Base_Type { get; set; }
        public DbSet<Material_Company> Material_Company { get; set; }
        public DbSet<Material_Product> Material_Product { get; set; }
        public DbSet<Material_Product_Company> Material_Product_Company { get; set; }
        public DbSet<Material_Type> Material_Type { get; set; }
    }
}
